variables:
  NODE_VERSION: "20.5.1"
  CYPRESS_IMAGE: "cypress/browsers:node20.5.1-chrome100-ff99-edge"

frontend-build:
  stage: frontend-build
  image: ${CYPRESS_IMAGE}
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest-8 --activate
    - pnpm config set store-dir .pnpm-store
  script:
    - cd frontend
    - pnpm install
    - pnpm build
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store

frontend-test:
  stage: frontend-test
  image: ${CYPRESS_IMAGE}
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest-8 --activate
    - pnpm config set store-dir .pnpm-store
  script:
    - cd frontend
    - pnpm install
    - pnpm test
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store

backend-test:
  stage: backend-test
  image: node:${NODE_VERSION}
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest-8 --activate
    - pnpm config set store-dir .pnpm-store
  script:
    - cd backend
    - pnpm install
    - pnpm test
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store