stages:
    - build
    - test

build:
    stage: build
    image: node:20.5.1
    before_script:
        - corepack enable
        - corepack prepare pnpm@latest-8 --activate
        - pnpm config set store-dir .pnpm-store
    script:
        - pnpm install
    cache:
        key:
            files:
                - pnpm-lock.yaml
        paths:
            - .pnpm-store

test:
    stage: test
    image: node:20.5.1
    before_script:
        - corepack enable
        - corepack prepare pnpm@latest-8 --activate
        - pnpm config set store-dir .pnpm-store
    script:
        - echo "TODO - testing should be done here
        - pnpm install
        - pnpm test
    cache:
        key:
            files:
                - pnpm-lock.yaml
        paths:
            - .pnpm-store
