stages:
    - build

variables:
    PNPM_VERSION: '8.7.1'

before_script:
    - apt-get update -qy
    - apt-get install -y curl
    - curl -fsSL https://deb.nodesource.com/setup_14.x | bash -
    - apt-get install -y nodejs
    - curl -fsSL https://get.pnpm.io/v${PNM_VERSION} | bash -
    - export PATH=./node_modules/.bin:$PATH

cache:
    paths:
        - node_modules/
        - ~/.pnpm-store

build:
    stage: build
    script:
        - pnpm install
        - pnpm build
